### ISSUE TITLE
Cannot npx without installing it globally

### ISSUE THREAD

**Issue by abernier** [itstheandre/lean-express-gen#33]
Generally speaking, I prefer not installing the global version of a package, but rather `npx` it so the latest version is used (if not declared as project's deps).

Despite `ironlauncher` is not installed globally on my machine, I'm prevented executing it with `npx` by this `WARNING` message :

```sh
$ npx ironlauncher foo
Need to install the following packages:
  ironlauncher
Ok to proceed? (y) y

⚠  WARNING  There is a new version of IronLauncher online.

Please update by running `npm i -g ironlauncher` in your terminal before you are able to run ironlauncher again
```

that kind of "force" me to install it globally

**Comment by itstheandre** [comment]
Hey @abernier  thank you for the message.

Actually this is caused by a current error in npm. please run the command with `npx ironlauncher@latest foo`. The goal you're trying to do will work as expected.

This is caused by a caching system by npm - not entirely sure, but its the only reason I've seen so far - and you're getting a previous version of the ironlauncher. As you can see in the [readme](https://github.com/ironhack-edu/ironlauncher/blob/master/README.md) we don't even encourage global installations anymore
